export class Settings {
  calculate: boolean = true;
  calculateStats: boolean = true;
  abilityNumbers: boolean = true;
  eliteFirst: boolean = true;
  expireConditions: boolean = true;
  applyConditions: boolean = true;
  activeApplyConditions: boolean = true;
  moveElements: boolean = true;
  hideStats: boolean = true;
  randomStandees: boolean = false;
  activeStandees: boolean = true;
  allyAttackModifierDeck: boolean = true;
  initiativeRequired: boolean = true;
  levelCalculation: boolean | undefined = undefined;
  levelAdjustment: number | undefined = undefined;
  bonusAdjustment: number | undefined = undefined;
  ge5Player: boolean | undefined = undefined;
  disableStandees: boolean = false;
  fullscreen: boolean = false;
  autoscroll: boolean = true;
  disableColumns: boolean = false;
  dragValues: boolean = true;
  hints: boolean = true;
  zoom: number = 100;
  barsize: number = 1;
  fontsize: number = 1;
  locale: string = "en";
  editionDataUrls: string[] = [];
  excludeEditionDataUrls: string[] = [];
  spoilers: string[] = [];
  browserNavigation: boolean = false;
  serverUrl: string | undefined;
  serverPort: number | undefined;
  serverPassword: string | undefined;
  serverAutoconnect: boolean = true;
  serverSettings: boolean = false;
  serverWss: boolean = false;
  maxUndo: number = 50;
}