name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Node 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: npm
      - name: npm i and npm test
        run: |
          npm ci
          npm test -- --watch=false
      - name: lint
        run: npm run lint
      - name: check formatting
        run: npm run format:check
